name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        # run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'

      - name: Build Wasm
        working-directory: ./wasm-game-state/
        run: wasm-pack build

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: './svelte-game-ui'

      - name: Install dependencies
        working-directory: ./svelte-game-ui
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        working-directory: ./svelte-game-ui
        run: npm run build --verbose


      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'svelte-game-ui/build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
